
spring:
  mail:
    host: smtp.gmail.com
    username: tranminhchien15052003@gmail.com
    password: pasrhwjxtqkqdrug
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true